DROP TABLE IF EXISTS MOVIES_ANALYSIS;

CREATE TABLE MOVIES_ANALYSIS (
	DIRECTOR_NAME TEXT,
	NUM_CRITIC_FOR_REVIEWS SMALLINT,
	DURATION SMALLINT,
	DOMESTIC_GROSS MONEY,
	GENRES TEXT,
	MOVIE_TITLE TEXT,
	NUM_VOTED_USERS INT,
	NUM_USER_FOR_REVIEWS SMALLINT,
	"language" TEXT,
	COUNTRY VARCHAR(50),
	CONTENT_RATING VARCHAR(20),
	BUDGET MONEY,
	TITLE_YEAR SMALLINT,
	IMDB_SCORE REAL
);

SET
	LC_MONETARY = 'en_US';

COPY MOVIES_ANALYSIS
FROM
	'D:\Projects\IMDb_Movies_Analysis\data\cleaned_movies.csv'
WITH
	(FORMAT CSV, HEADER TRUE);

SELECT
	*
FROM
	MOVIES_ANALYSIS;